### ISSUE TITLE
Using gulp-mocha I get a syntax error thrown by this module.

### ISSUE THREAD

**Issue by nackjicholson** [sindresorhus/beeper#5]
```
[16:25:30] SyntaxError: /Users/nackjicholson/repos/dynamoDb-marshaler/node_modules/gulp-mocha/node_modules/gulp-util/node_modules/beeper/index.js: 'return' outside of function (9:1)
   7 |  process.argv.indexOf('--beep=false') !== -1) {
   8 |  module.exports = function () {};
>  9 |  return;
     |  ^
  10 | }
  11 | 
  12 | function beep() {
```

This is running iojs v1.8.1

**Comment by nackjicholson** [comment]
Note, might be a babel compilation issue as well. I just don't know, something is choking here though.

**Comment by sindresorhus** [comment]
Sounds like a babel compile error indeed. Well, you're doing it wrong, you should never try to compile dependencies. That will definitely break.

Top level return is totally valid in Node, since node wraps all modules in a IIFE, so it's not really top level: https://github.com/sindresorhus/beeper/blob/77863ffead2c32a073a65caef3169b6264ba0c8c/index.js#L9

**Comment by nackjicholson** [comment]
I'm just trying to compile tests.

**Comment by nackjicholson** [comment]
Was indeed a babel error, though https://github.com/babel/babel/issues/1398
